# Generated by Django 4.0 on 2025-03-18 06:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('auth_id', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('download_url', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('storage_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrashBin',
            fields=[
                ('id', models.CharField(max_length=55, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('location_x', models.IntegerField(blank=True)),
                ('locaiton_y', models.IntegerField(blank=True)),
                ('binType', models.CharField(blank=True, default=None, max_length=55, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.appuser')),
                ('images', models.ManyToManyField(blank=True, default=None, null=True, to='app.ImageModel')),
            ],
        ),
    ]
