# Generated by Django 4.0 on 2025-03-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_imagemodel_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinCategory',
            fields=[
                ('id', models.CharField(max_length=55, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Bin Categories',
            },
        ),
        migrations.RemoveField(
            model_name='trashbin',
            name='binType',
        ),
        migrations.AddField(
            model_name='trashbin',
            name='categories',
            field=models.ManyToManyField(blank=True, to='app.BinCategory'),
        ),
    ]
