# Generated by Django 4.0 on 2025-03-19 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_bincategory_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trashbin',
            old_name='locaiton_y',
            new_name='location_y',
        ),
    ]
